language: python
sudo: false
dist: xenial

python: []
  # - '3.5'
  # - 'nightly'
  # - 'pypy'
  # - 'pypy3'

matrix:
  allow_failures:
    - python: 'nightly'

  include:
    # - python: '3.7-dev'
    #   env:
    #     - TEST_ENTITY_SERVICE=https://testing.es.data61.xyz
    #     - MYPY_TYPING=1
    #     - INCLUDE_CLI=1
    # - python: '3.6'
    #   env:
    #     - TEST_ENTITY_SERVICE=https://testing.es.data61.xyz
    #     - MYPY_TYPING=1
    #     - INCLUDE_CLI=1
    # - python: '2.7'
    #   env:
    #     - TEST_ENTITY_SERVICE=https://testing.es.data61.xyz
    #     - INCLUDE_CLI=1
    # OSX + Python is not officially supported by Travis CI as of September 2018
    # nevertheless, "nightly" and some "*-dev" versions seem to work, so we
    # include them explicitly.
    # They only seem to work with the xcode8.3 image, and not the newer ones.
    # Thus we will leave this in, until it breaks one day, at which point we
    # will probably remove testing on OSX if it is not supported then.
    - os: osx
      language: generic
      env:
        # Latest Python 2.7 from Homebrew
        - PYV=2.7.15
    - os: osx
      language: generic
      env:
        - PYV=3.5.6
    - os: osx
      language: generic
      env:
        - PYV=3.6.6
    - os: osx
      language: generic
      env:
        - PYV=3.7.0

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        brew update
        if ! brew list --versions pyenv >/dev/null; then
            brew install pyenv
        elif ! brew outdated pyenv; then
            brew upgrade pyenv
        fi
        pyenv install $PYV
        pyenv global $PYV
    fi
  - if [ "${MYPY_TYPING}" == "1" ]; then travis_retry pip install mypy; fi
  - travis_retry pip install codecov
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -e .

script:
  - if [ "${MYPY_TYPING}" == "1" ]; then mypy clkhash --ignore-missing-imports --no-implicit-optional --disallow-untyped-calls; fi
  - pytest --cov=clkhash
  - codecov
