triggers:
  batch: true
  branches: none
    include:
    - *
  pr:
    include:
    - *

jobs:
- template: .azurePipeline/wholeBuild.yml  # Template reference
  parameters:
    pythonVersions: ['3.7', '3.6', '3.5', '2.7']
#    operatingSystems: ['ubuntu-16.04', 'macos-10.13', 'vs2017-win2016']
    operatingSystems: ['vs2017-win2016']
    architectures: ['x64', 'x86']

