trigger:
  branches: 
    include:
    - master
    exclude:
    - '*'
  tags:
    include:
    - 'v*'
pr:
  branches:
    include:
    - '*'

jobs:
- template: .azurePipeline/wholeBuild.yml  # Template reference
  parameters:
    pythonVersions: ['3.7', '3.6', '3.5', '2.7']
#    operatingSystems: ['ubuntu-16.04', 'macos-10.13', 'vs2017-win2016']
    operatingSystems: ['vs2017-win2016']
    architectures: ['x64', 'x86']

- job:
  steps:
  - script: echo "##vso[build.addbuildtag] Automated"
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
#  - script: |
#      pip install twine
#      twine upload -u $(PYPI_LOGIN) -p $(PYPI_PASSWORD) --skip-existing dist/*.whl
#    displayName: 'Send artifact to Pypi'
#    condition: only if commit is tagged... will be fun to check
