trigger:
  branches: 
    include:
    - master
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

jobs:
- template: .azurePipeline/wholeBuild.yml  # Template reference
  parameters:
    pythonVersions: ['3.7', '3.6', '3.5', '2.7']
#    operatingSystems: ['ubuntu-16.04', 'macos-10.13', 'vs2017-win2016']
    operatingSystems: ['vs2017-win2016']
    architectures: ['x64', 'x86']
    pythonVersionMypy: '3.7' # This will be the only version of Python for which we will run mypy. Be sure it is also part of the list pythonVersions

- job:
  displayName: "Check Git Tags"
  steps:
# In this step, if this build is triggered by a tag, it will add a tag 'Automated' to the current build.
  - script: echo "##vso[build.addbuildtag]Automated"
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
